### ISSUE TITLE
job result show error.

### ISSUE THREAD

**Issue by seanly** [oliverdunk/SaltGUI#1]
![image](https://cloud.githubusercontent.com/assets/232069/20104041/588834fa-a607-11e6-8657-a7e2faab6b6d.png)

**Comment by seanly** [comment]
i use state.show_sls

**Comment by oliverdunk** [comment]
Thanks for letting me know. The problem is that the API returns inconsistent responses for the same method based on which command has been run, which makes it hard to code an interface for. I do plan on revisiting this eventually, but hopefully you understand the reason I'm not fixing it immediately. PRs always welcome.
